<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="42" started-at="2019-04-25T14:57:11Z" finished-at="2019-04-25T14:57:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="42" started-at="2019-04-25T14:57:11Z" finished-at="2019-04-25T14:57:11Z">
      <class name="com.com.firstselenium.testngclass">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.com.firstselenium.testngclass@394e1a0f]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-04-25T14:57:11Z" finished-at="2019-04-25T14:57:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="green()[pri:0, instance:com.com.firstselenium.testngclass@394e1a0f]" name="green" duration-ms="14" started-at="2019-04-25T14:57:11Z" finished-at="2019-04-25T14:57:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- green -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.com.firstselenium.testngclass@394e1a0f]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-04-25T14:57:11Z" finished-at="2019-04-25T14:57:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.com.firstselenium.testngclass@394e1a0f]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-04-25T14:57:11Z" finished-at="2019-04-25T14:57:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="orange()[pri:0, instance:com.com.firstselenium.testngclass@394e1a0f]" name="orange" duration-ms="2" started-at="2019-04-25T14:57:11Z" depends-on-methods="com.com.firstselenium.testngclass.green" finished-at="2019-04-25T14:57:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.com.firstselenium.testngclass.orange(testngclass.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orange -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.com.firstselenium.testngclass@394e1a0f]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-04-25T14:57:11Z" finished-at="2019-04-25T14:57:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="wight()[pri:0, instance:com.com.firstselenium.testngclass@394e1a0f]" name="wight" duration-ms="0" started-at="2019-04-25T14:57:11Z" depends-on-methods="com.com.firstselenium.testngclass.orange" finished-at="2019-04-25T14:57:11Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testngclass.wight()[pri:0, instance:com.com.firstselenium.testngclass@394e1a0f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testngclass.wight()[pri:0, instance:com.com.firstselenium.testngclass@394e1a0f] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wight -->
        <test-method status="SKIP" signature="blue()[pri:0, instance:com.com.firstselenium.testngclass@394e1a0f]" name="blue" duration-ms="0" started-at="2019-04-25T14:57:11Z" depends-on-methods="com.com.firstselenium.testngclass.wight" finished-at="2019-04-25T14:57:11Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testngclass.blue()[pri:0, instance:com.com.firstselenium.testngclass@394e1a0f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testngclass.blue()[pri:0, instance:com.com.firstselenium.testngclass@394e1a0f] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- blue -->
      </class> <!-- com.com.firstselenium.testngclass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
